args: !!python/object:argparse.Namespace
  augmentation: true
  batch_size: 2
  config: config/all_tooth.yaml
  delta: 0.1667
  div_factor: 25
  dropout: 0.0
  dynamic: false
  emb_dims: 1024
  experiment: all_tooth
  final_div_factor: 1e4
  global_pool_backbone: avg
  gpus: 1
  input_channels: 15
  k: 16
  load_from_checkpoint: null
  lr_max: 0.001
  max_epochs: 50
  n_edgeconvs_backbone: 5
  norm: instance
  num_points: 8000
  output_channels: 17
  pct_start: 0.1
  resume_from_checkpoint: null
  root_dir: F:/dataset/Teeth3DS/data
  seed: 0
  split_dir: F:/dataset/Teeth3DS/split
  start_epoch: 0
  test_file: testing_all.txt
  test_workers: 1
  train_file: training_all.txt
  train_workers: 1
  use_stn: false
  val_file: testing_all.txt
  val_workers: 1
  weight_decay: 0.0001
