args: !!python/object:argparse.Namespace
  augmentation: true
  batch_size: 1
  config: config/all_tooth.yaml
  delta: 0.5
  div_factor: 25
  dropout: 0.0
  dynamic: false
  emb_dims: 1024
  experiment: all_tooth
  final_div_factor: 1e4
  global_pool_backbone: avg
  gpus: 1
  input_channels: 15
  k: 16
  load_from_checkpoint: null
  lr_max: 0.001
  max_epochs: 50
  n_decoder: 1
  n_edgeconvs_backbone: 5
  norm: instance
  normalize_pc: false
  num_points: 9998
  output_channels: 17
  pct_start: 0.1
  query_num: 30
  resume_from_checkpoint: null
  root_dir: D:/dataset/Teeth_box/data
  seed: 0
  split_dir: D:/dataset/Teeth_box
  start_epoch: 0
  test_file: test.txt
  test_workers: 2
  train_file: train.txt
  train_workers: 2
  use_stn: false
  val_file: val.txt
  val_workers: 2
  weight_decay: 0.0001
