args: !!python/object:argparse.Namespace
  anno_root: E:/dataset/3DTeethLand/Batch_2_4_23_24
  augmentation: true
  batch_size: 1
  class_name: airplane
  config: config/tooth_landmark.yaml
  debug: false
  div_factor: 25
  dropout: 0.0
  dynamic: false
  emb_dims: 1024
  experiment: tooth_landmark
  final_div_factor: 1e4
  global_pool_backbone: avg
  gpus: 1
  input_channels: 15
  k: 20
  landmark_std: 0.5
  load_from_checkpoint: null
  lr_max: 0.0001
  max_epochs: 50
  n_decoder: 1
  n_edgeconvs_backbone: 5
  norm: instance
  normalize_pc: false
  num_points: 5000
  patch_root: E:/dataset/3DTeethLand/patches
  pct_start: 0.1
  query_num: 50
  resume_from_checkpoint: null
  seed: 0
  split_root: E:/dataset/3DTeethLand
  start_epoch: 0
  test_file: test.txt
  test_workers: 0
  train_file: train.txt
  train_workers: 0
  val_file: test.txt
  val_workers: 0
  weight_decay: 0.0001
