GENERAL:
  experiment: tooth_landmark
  seed: 0

DATA:
  # data path
  anno_root: D:/dataset/3DTeethLand/Batch  # Batch_2_4_23_24
  split_root: D:/dataset/3DTeethLand
  patch_root: D:/dataset/3DTeethLand/patches
  # sample
  class_name: airplane
  num_points: 10000
  # augmentation
  augmentation: True
  normalize_pc: False
  # landmark
  landmark_std: 0.5

STRUCTURE:
  k: 20
  input_channels: 15
  query_num: 50
  n_decoder: 1
  n_edgeconvs_backbone: 5
  emb_dims: 1024
  global_pool_backbone: avg  # max or avg
  norm: instance
  dynamic: False
  dropout: 0.

TRAIN:
  max_epochs: 50
  weight_decay: 0.0001
  # batch_size per gpu
  batch_size: 1
  load_from_checkpoint:
  resume_from_checkpoint:

  # one cycle lr scheduler
  lr_max: 0.0001 #0.0001
  pct_start: 0.1    # percentage of the cycle spent increasing lr
  div_factor: 25    # determine the initial lr (lr_max / div_factor)
  final_div_factor: 1e4 #1e4   # determine the final lr (lr_max / final_div_factor)
  start_epoch: 0

  train_file: train.txt
  train_workers: 0  # 2

  val_file: test.txt
  val_workers: 0  # 2

  test_file: test.txt
  test_workers: 0

  debug: False
